### PR TITLE
Use Docker to run mongoexport so that MongoDB versions line up

### PR DESCRIPTION
**Pull request by Sammidysam**
Trello: https://trello.com/c/ocQh5uQ6/67-use-docker-in-database-export-script-to-ensure-equal-mongo-versions

I will not merge this until @acrap5 tests out the process as mentioned in #4 on this branch and it actually works.  It is nice if others test it too, but I don't see it as quite as crucial.

### CODE REVIEW

**Comment by acrap5** [comment]
Still having errors when trying to rebuild my cwd container. See:
https://pastebin.com/rvCURm3j
https://pastebin.com/a7VbXSC9

for full error logs.

**Comment by Sammidysam** [comment]
These are private pastes.  Please let me know how best to view them.

**Comment by acrap5** [comment]
Changed their privacy, should be good to view them now.

**Comment by Sammidysam** [comment]
@acrap5 Could you try incorporating the changes that were made on the `develop` branch and trying again?  You could try applying this specific commit.
https://github.com/EnvironmentalDashboard/citywide-dashboard.alpha/commit/8fcf504e39d47cf3728b72f83fb181daa35597ff
It is possible this was fixed in the past.

**Comment by Sammidysam** [comment]
@Terf Did you happen to get errors when trying to build on the Environmental Dashboard server?  I figure it was on the Community Hub server, but I'm just looking to see if I have access to any environment where errors come up so that I can have more of an ability to debug everything.

**Comment by Terf** [comment]
@Sammidysam I don't think I've ever built CWD on the ED server but I encountered no errors when deploying on CH tho I didn't really test the code this branch references e.g. `download-prod.sh`

**Comment by Sammidysam** [comment]
@Terf I thought you tried to test `download-prod.sh` at one point and it failed on your Linux installation.  Hmm, okay.  I'm not sure how best I can help @acrap5 fix these build errors.

**Comment by Terf** [comment]
Oh yeah... I do think I remember trying quickly once and it didn't work but I ended up not really needing it since you added those env vars I could just point to the db that's already up but if you're just looking to reproduce a Linux installation you could use the ED server or just spin up a ubuntu container locally `docker run -ti ubuntu bash`

**Comment by acrap5** [comment]
Tried applying the commit you suggested and when I tried to run ./download-prod.sh, I got the following error:

https://pastebin.com/c869YBzi

I'm not entirely certain, but I think this is the error I was having that was fixed by the changes in this branch. Or at least, it's similar to one I was having before. In any case, applying those changes from the develop branch seem to have set me back even further. That is, in this branch I'm able to successfully run download-prod.sh and upload-prod.sh, but get caught up when rebuilding my cwd container.

**Comment by Sammidysam** [comment]
@acrap5 Please try adjusting the `mongoexport` command like so https://aug2uag.blogspot.com/2018/08/mongoexport-unrecognized-field-snapshot.html and let me know if then the import of your dump goes better.

**Comment by acrap5** [comment]
@Sammidysam I've gotten this working on my system. I believe there was an issue with my Webpack installation. The fixes in this branch do fix what they're supposed to (issues with mongodump) and should so I think this pull request can be merged now!

**Comment by Sammidysam** [comment]
@acrap5 Are the issues with your Webpack installation anything that you see as reasonable for another user to encounter?  I think if you see it likely to occur for anyone else, we should probably make some documentation here for how to fix the error.

I am merging regardless - glad you got this sorted out!!

**Pull request merged**
