### PR TITLE
Section title on right

### PR DESCRIPTION
**Pull request by acrap5**
This branch adds a variable "SHOW_ONE_TITLE" that, if true, moves the view buttons to the right, and show's only one at a time. If the views are locked (hash in URL), then the view button will only changed when clicked, otherwise the views will rotate through like normal.

### CODE REVIEW

**Comment by acrap5** [comment]
https://trello.com/c/4nUjFVWS/6-add-option-to-have-title-of-a-section-above-the-gauges

**Comment by Sammidysam** [comment]
Merging first and asking questions later

**Comment by Sammidysam** [comment]
Found bug: when clicking on section title to change to a different section, the URL updating is one off in the array relative to what it should be.  This should make sense if you test it sometime.

**Comment by oliverripps** [comment]
This may have been fixed or may have something to do with my localhost, but when testing my URL never changes no matter how much you click on the buttons.

**Comment by oliverripps** [comment]
I can't find any other issues, other than maybe the buttons being slightly off-center but if I remember correctly that was part of a separate issue.

**Comment by acrap5** [comment]
@oliverripps the URL will only, and should only, change if it starts off with a hash in it, meaning it's in view locked mode. Otherwise the views will rotate as normal, and the URL will not change regardless of clicking. Could you confirm that it behaves this way on your machine by testing it with and without a hash (either "#glsc", "#air", or "#lake").

**Comment by oliverripps** [comment]
I tested it on my machine with and without the hash and it seems to be working as it should. It is locked when a hash is present with a category and rotates otherwise.

**Comment by Sammidysam** [comment]
@oliverripps The Trello card will always (as long as everyone is doing their job) have the necessary descriptions of the feature in order to be able to test it against its expected behavior.  Not sure if you consulted the card before testing this, but just a note for the future.

**Pull request merged**
