### PR TITLE
change to one water droplet in the pipes

### PR DESCRIPTION
**Pull request by adartulloch**
This PR modifies water-droplet animation so that only one water droplet appears in the pipes during the lake view. This animation occurs in the `styleSheet.css` file, and @Sammidysam realized we would want there to be an entry in the database corresponding to the number of water droplets, providing scalability, but I can't think of an immediate solution to that. Thoughts?

### CODE REVIEW

**Comment by Sammidysam** [comment]
Yeah, there doesn't seem to be an elegant way to do this because we are using normal CSS and not JavaScript-generated CSS (like React would have us do).

I think this block can make it programmatic: https://github.com/EnvironmentalDashboard/citywide-dashboard.alpha/blob/2ecbcd58486d3f2ddbe14657b241da22c1946b9d/cwd/app.js#L226

For each animation, you can set this display rule (the one you changed in this PR) from JavaScript for each element based on the view's data.  Note that this would involve changing a view from having a string list of animations to an object list of animations.

It's unfortunate, but it would indeed do the job, I believe.

**Comment by Sammidysam** [comment]
@adartulloch Since it's been a week, do you intend on making this customizable in the database or should I assume that we will just hardcode it to one droplet?

**Comment by adartulloch** [comment]
On further consideration, I may just have to hardcode this, as jQuery's selection ruling isn't being very helpful to me despite my efforts over the last few hours  -_-
...unless you can try to make sense of the CSS class names here (I want to select `.flowable path:last-of-type, .flowable line:last-of-type` in `styleSheet.css` and change the field `stroke-dasharray` to a custom string).

**Comment by Sammidysam** [comment]
My idea is you can copy and paste that rule - did `$('.flowable path:last-of-type, .flowable line:last-of-type')` not work?  Then you could loop over the elements that come back.

Screen Shot 2020-07-09 at 4 27 07 PM
This is my idea, though I seem to have been a little bit wrong.

**Comment by Sammidysam** [comment]
If you did try this and not have luck, we can probably punt on this for now.  JavaScript within CSS would make this *so* much easier - it's a shame they didn't use new technology.

**Comment by adartulloch** [comment]
Yes, tried to no avail unforunately.

**Comment by Sammidysam** [comment]
@adartulloch Take a look at the commit I made and see if it helps toward a breakthrough.  We just need to set that property per a view or glyph (probably view is fine).  Could you generate the string based on a number coming from the view object?

**Comment by adartulloch** [comment]
Oh that's so awesome! I can definitely generate a string now.

**Comment by adartulloch** [comment]
Added an attribute `num_droplets` under the `lake.view`
Screen Shot 2020-07-21 at 10 36 48 AM

**Comment by Sammidysam** [comment]
@adartulloch What about when `view.num_droplets` (I wonder if renaming this to just `droplets` may be fine) is not defined? (As it won't be for the other views) I figure this would cause a console error?  I figure we need to run the line within `if (view.droplets)`?

**Comment by Sammidysam** [comment]
I guess `num_droplets` makes the most sense so can keep that name.

**Comment by adartulloch** [comment]
Yeah, tested that earlier and found that the console actually doesn't give an error. Can't hurt to add that check though.

**Pull request merged**
